// Generated by CoffeeScript 1.4.0
(function() {

  describe("Something sweet", function() {
    it("should be really sweet", function() {
      return expect(sweet).toBeTruthy;
    });
    return it("should return the right statement", function() {
      return expect(sweet()).toBe("this function is really sweet");
    });
  });

}).call(this);
